from enum import Enum


class UserRole(str, Enum):
    PATIENT = "PATIENT"
    CAREGIVER = "CAREGIVER"
    DOCTOR = "DOCTOR"
    HOSPITAL = "HOSPITAL"


class RiskLevel(str, Enum):
    NORMAL = "NORMAL"
    WARNING = "WARNING"
    HIGH_RISK = "HIGH_RISK"


class EmergencyStatus(str, Enum):
    DETECTED = "DETECTED"
    SUPERVISION = "SUPERVISION"
    VERIFICATION = "VERIFICATION"
    CANCELLED = "CANCELLED"
    CONFIRMED = "CONFIRMED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESPONDING = "RESPONDING"
    RESOLVED = "RESOLVED"


class MotionState(str, Enum):
    STATIONARY = "STATIONARY"
    ACTIVE = "ACTIVE"
    UNKNOWN = "UNKNOWN"


class PanicAttackType(str, Enum):
    EXPECTED_SITUATIONAL = "EXPECTED_SITUATIONAL"
    UNEXPECTED_SPONTANEOUS = "UNEXPECTED_SPONTANEOUS"
    NOCTURNAL = "NOCTURNAL"
    LIMITED_SYMPTOM = "LIMITED_SYMPTOM"
    RECURRENT = "RECURRENT"
    NONE_DETECTED = "NONE_DETECTED"
    UNKNOWN = "UNKNOWN"


class PatientResponse(str, Enum):
    OK = "OK"
    NEED_HELP = "NEED_HELP"
    NO_RESPONSE = "NO_RESPONSE"


class EscalationStage(str, Enum):
    NONE = "NONE"
    PATIENT_ALERTED = "PATIENT_ALERTED"
    CONTACT_NOTIFIED = "CONTACT_NOTIFIED"
    HOSPITAL_ESCALATED = "HOSPITAL_ESCALATED"
    AMBULANCE_REQUESTED = "AMBULANCE_REQUESTED"


class ReadingSource(str, Enum):
    BLE = "BLE"
    DEMO = "DEMO"
    WEARABLE = "WEARABLE"


class ConsentStatus(str, Enum):
    REQUESTED = "REQUESTED"
    GRANTED = "GRANTED"
    REJECTED = "REJECTED"
    REVOKED = "REVOKED"
    EXPIRED = "EXPIRED"

